---
title: Requirement Adoption Report for {{pkg_name}}
author: {{author}}
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    fig_crop: false
vignette: >
  %\VignetteIndexEntry{Requirement Adoption Report}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown_notangle}
header-includes:
  - \usepackage{array}
  - \usepackage{float}
  - \usepackage{multirow}
  - \usepackage{longtable}
---


```{r, setup, echo=FALSE,warning=FALSE}
suppressPackageStartupMessages({
  library(valtools)
  library(knitr)
  library(kableExtra)
  library(magrittr)
  library(devtools)
  library({{pkg_name}})
})

opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = TRUE,
  echo = FALSE,
  results = "asis",
  message = FALSE,
  tidy = FALSE
)

options(
  knitr.kable.NA = '',
  knitr.duplicate.label = "allow"
)

```

```{r shared-obj}
all_sig <- vt_scrape_sig_table() 
```

\newpage

# Certifications

## Signatures

**APPROVAL** I have reviewed this document and approve its content.

```{r sig-block}

all_sig[tolower(all_sig$role) != "validation lead",] %>%
  set_rownames(seq_len(nrow(.))) %>% 
  vt_kable_sig_table()

```

The effective date of this document is the last date of signature.

\newpage

# Release details

## Package Information

### Change Log

```{r change-log-table}
vt_scrape_change_log() %>% 
  vt_kable_change_log()
```


## Authors


```{r req-authors}
vt_scrape_requirement_editors() %>% 
  vt_kable_requirement_editors()
```


# Risk Assessment

```{r risk}
vt_scrape_risk_assessment() %>% 
  vt_kable_risk_assessment()
```

\newpage

# Requirements

```{r child-files-evaluation}
child_files <- vt_get_child_files() %>% 
  extract(grepl(tolower(.), pattern = 'req'))
vt_file(vt_path(child_files), dynamic_referencing = {{enable_dynamic_referencing}})
```
