---
title: Validation Report for {{pkg_name}}
author: {{author}}
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    fig_crop: false
vignette: >
  %\VignetteIndexEntry{Validation Report}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown_notangle}
header-includes:
  - \usepackage{array}
  - \usepackage{float}
  - \usepackage{multirow}
---

```{r, setup, echo=FALSE,warning=FALSE}
suppressPackageStartupMessages({
  library(valtools)
  library(knitr)
  library(kableExtra)
  library(magrittr)
  library(devtools)
  library({{pkg_name}})
})

opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = TRUE,
  echo = FALSE,
  results = "asis",
  message = FALSE,
  tidy = FALSE
)

options(knitr.kable.NA = '')

```

\newpage

# Certifications

## Signatures

**APPROVAL** I have reviewed this document and approve its content.

```{r other-roles-sig-block}

vt_scrape_sig_table()  %>% 
  vt_kable_sig_table()

```

The effective date of this document is the last date of signature.

\newpage

# Release details

## Package Information

### Change Log

```{r change-log-table}
vt_scrape_change_log() %>% 
  vt_kable_change_log()
```

### Validation Environment

```{r env-table}
vt_scrape_val_env() %>% 
  vt_kable_val_env()
```

## Authors

### Requirements 

```{r}
vt_scrape_requirement_editors() %>% 
  vt_kable_requirement_editors()

```

### Functions

```{r func}

## report all functions, exported or not, with editor information
vt_scrape_function_editors(tags = c("editor", "editDate")) %>%
 vt_kable_function_editors()

# include only exported function details
# all_func_details <- vt_scrape_function_editors()
# all_func_details[!is.na(all_function_details$export), c("functions", "editor", "editDate")] %>% 
#   vt_kable_functions()
#   
```

### Test Case Authors

```{r}

vt_scrape_test_case_editors() %>%
 vt_kable_test_case_editors()

```

### Test Code Authors

```{r}

vt_scrape_test_code_editors() %>%
 vt_kable_test_code_editors()

```

## Traceability

```{r}

vt_scrape_coverage_matrix() %>% 
 vt_kable_coverage_matrix()

```

\newpage

# Validation

```{r child-files}
child_files <- vt_get_child_files()
vt_file(vt_path(child_files),dynamic_referencing = {{enable_dynamic_referencing}})
```

